name: "Java CI"
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
env:
  GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
  GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}
jobs:
  test_project:
    name: "Test Project"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        java: [17, 21]
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run tests"
        run: ./gradlew check
      - name: "🏃 Run integration tests"
        working-directory: ./examples/testapp1
        run: ./gradlew integrationTest
  publish_snapshot:
    name: "Build Project and Publish Snapshot release"
    runs-on: ubuntu-24.04
    if: github.event_name == 'push'
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build Project"
        run: ./gradlew build
      - name: "📤 Publish Snapshot version to Artifactory (repo.grails.org)"
        if: success()
        env:
          GRADLE_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_USERNAME: ${{ secrets.MAVEN_PUBLISH_USERNAME }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.MAVEN_PUBLISH_PASSWORD }}
          MAVEN_PUBLISH_URL: ${{ secrets.MAVEN_PUBLISH_SNAPSHOT_URL }}
        run: ./gradlew publish
      - name: "📖 Generate Snapshot Documentation"
        if: success()
        run: ./gradlew docs
      - name: "📤 Publish Snapshot Documentation to Github Pages"
        if: success()
        uses: grails/github-pages-deploy-action@grails
        env:
          BRANCH: gh-pages
          COMMIT_EMAIL: ${{ env.GIT_USER_EMAIL }}
          COMMIT_NAME: ${{ env.GIT_USER_NAME }}
          FOLDER: build/docs/manual
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
